### ISSUE TITLE
Error: Text file busy

### ISSUE THREAD

**Issue by lexizz** [yii2tech/html2pdf#20]
```
2019-06-19 10:52:44 [error][yii\base\ErrorException:2] yii\base\ErrorException: unlink(project/runtime/html2pdf/html2pdf5d09cdac4814a4.39909384.pdf): Text file busy in project/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:407
Stack trace:
#0 project/vendor/yii2tech/html2pdf/src/TempFile.php(98): yii\helpers\BaseFileHelper::unlink()
#1 project/vendor/yii2tech/html2pdf/src/TempFile.php(36): yii2tech\html2pdf\TempFile->delete()
#2 project/controllers/FilesController.php(91): yii2tech\html2pdf\TempFile->__destruct()
#3 project/vendor/yiisoft/yii2/base/InlineAction.php(57): app\controllers\FilesController->actionAct()
#4 project/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{project/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#5 project/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#6 project/vendor/yiisoft/yii2/base/Module.php(528): app\controllers\FilesController->runAction()
#7 project/vendor/yiisoft/yii2/web/Application.php(103): yii\web\Application->runAction()
#8 project/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#9 project/web/index.php(10): yii\web\Application->run()
#10 {main}
```
Usages:
``` 
// FilesController.php
$response = \Yii::$app->html2pdf->render('upload', [
            'upload' => $upload,
            'company' => $company,
            'otherData' => $otherData,
            'format' => new Format(),
        ])->send(uniqid('', true) . '.pdf');

return $response;
```
``` 
// upload.php
<a class="download-doc" href="<?= \yii\helpers\Url::to([
                                        '/files/act',
                                        'upload_id' => $upload->id,
                                ]) ?>"><i class="icon"></i>Скачать документ</a>
```
Possible reasons:
No closed an open file pointer in class TempFile method send

Component | Version
html2pdf | 1.0.5
Yii | 2.0.15.1
Composer | 1.6.5
PHP | 7.2.12
Operating system | Vagrant  2.2.3 / CentOS Linux release 7.6.1810

**Comment by klimov-paul** [comment]
Unable to reproduce
